import { useState,FormEvent } from 'react';import { useParams } from 'react-router-dom';import { useResource,useWrite } from '../lib/queries';import { Modal } from '../components/ui/Modal';import { QueryState } from '../components/ui/QueryState';
const localInput=(date:string)=>new Date(+new Date(date)-new Date(date).getTimezoneOffset()*60000).toISOString().slice(0,16);
export default function Calendar(){
 const {workspaceId}=useParams();const base='/workspaces/'+workspaceId;const [anchor,setAnchor]=useState(new Date());const [view,setView]=useState('month');const [selected,setSelected]=useState<any>(null);const write=useWrite();
 const start=new Date(anchor);start.setHours(0,0,0,0);if(view==='month')start.setDate(1);if(view==='week')start.setDate(start.getDate()-start.getDay());const end=new Date(start);if(view==='month')end.setMonth(end.getMonth()+1);else end.setDate(end.getDate()+(view==='week'?7:1));
 const events=useResource<any[]>(base+'/events?from='+encodeURIComponent(start.toISOString())+'&to='+encodeURIComponent(end.toISOString()));
 const days=Array.from({length:view==='month'?new Date(anchor.getFullYear(),anchor.getMonth()+1,0).getDate():view==='week'?7:1},(_,i)=>{const date=new Date(start);date.setDate(date.getDate()+i);return date;});
 function move(direction:number){const next=new Date(anchor);if(view==='month')next.setMonth(next.getMonth()+direction);else next.setDate(next.getDate()+direction*(view==='week'?7:1));setAnchor(next);}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await write.mutateAsync({path:base+'/events'+(selected.id?'/'+selected.id:''),method:selected.id?'PATCH':'POST',body:{title:f.get('title'),startAt:new Date(String(f.get('startAt'))).toISOString(),endAt:new Date(String(f.get('endAt'))).toISOString(),allDay:f.get('allDay')==='on',location:f.get('location'),recurrence:f.get('recurrence')}});setSelected(null);}
 return <><div className="page-heading"><div><h1>Calendar</h1><p>A clear view of your time.</p></div><button className="primary" onClick={()=>setSelected({})}>+ New event</button></div><div className="row" style={{marginBottom:20}}><div className="actions"><button className="secondary" aria-label="Previous period" onClick={()=>move(-1)}>?</button><h3>{anchor.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h3><button className="secondary" aria-label="Next period" onClick={()=>move(1)}>?</button></div><select value={view} aria-label="Calendar view" onChange={e=>setView(e.target.value)} style={{maxWidth:130}}>{['month','week','day'].map(v=><option key={v}>{v}</option>)}</select></div><QueryState query={events}/><div className={view==='day'?'stack':'calendar-grid'}>{view==='month'&&Array.from({length:start.getDay()},(_,i)=><div key={'blank'+i} className="calendar-day"/>)}{days.map(date=><section key={date.toISOString()} className={view==='day'?'panel':'calendar-day'}><h3>{date.toLocaleDateString(undefined,{weekday:'short',day:'numeric'})}</h3>{events.data?.filter(e=>new Date(e.startAt).toDateString()===date.toDateString()).map(e=><button key={e.occurrenceId||e.id} onClick={()=>setSelected(e)}>{e.allDay?'All day':new Date(e.startAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} ? {e.title}</button>)}</section>)}</div><Modal isOpen={!!selected} onClose={()=>setSelected(null)} title={selected?.id?'Edit event series':'New event'}>{selected&&<form onSubmit={e=>void save(e).catch(()=>{})}><label>Title<input name="title" required defaultValue={selected.title}/></label><div className="field-grid"><label>Starts<input type="datetime-local" name="startAt" required defaultValue={selected.startAt?localInput(selected.startAt):''}/></label><label>Ends<input type="datetime-local" name="endAt" required defaultValue={selected.endAt?localInput(selected.endAt):''}/></label></div><label><span><input type="checkbox" name="allDay" defaultChecked={selected.allDay}/> All day</span></label><label>Location<input name="location" defaultValue={selected.location}/></label><label>Repeats<select name="recurrence" defaultValue={selected.recurrence||''}><option value="">Does not repeat</option><option value="FREQ=DAILY">Daily</option><option value="FREQ=WEEKLY">Weekly</option><option value="FREQ=MONTHLY">Monthly</option></select></label><div className="actions"><button className="primary" disabled={write.isPending}>Save event</button>{selected.id&&<button type="button" className="danger" onClick={()=>write.mutate({path:base+'/events/'+selected.id,method:'DELETE'},{onSuccess:()=>setSelected(null)})}>Delete series</button>}</div></form>}</Modal></>;
}
