import { useState } from 'react';import { useParams,Link } from 'react-router-dom';import { Responsive,WidthProvider,Layout } from 'react-grid-layout';
import { useResource,useWrite } from '../lib/queries';import { Drawer } from '../components/ui/Modal';import { QueryState } from '../components/ui/QueryState';import { useUI } from '../stores/ui';
const Grid=WidthProvider(Responsive);
const registry:Record<string,{module:string;title:string;render:(data:any,base:string)=>React.ReactNode}>={
 task_list:{module:'tasks',title:'Tasks',render:(d,b)=>d.tasks?.length?d.tasks.slice(0,5).map((t:any)=><div key={t.id} className="item"><Link to={b+'/tasks'} className={t.status==='done'?'completed':''}>{t.title}</Link><p className="muted">{t.priority}</p></div>):<p>No tasks yet. Start with one small step.</p>},
 calendar_today:{module:'calendar',title:'Today?s agenda',render:(d,b)=>d.agenda?.events.length?d.agenda.events.slice(0,5).map((e:any)=><div className="item" key={e.occurrenceId||e.id}><Link to={b+'/calendar'}>{e.title}</Link><p className="muted">{new Date(e.startAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</p></div>):<p>Your calendar is clear today.</p>},
 notes_recent:{module:'notes',title:'Recent notes',render:(d,b)=>d.notes?.length?d.notes.slice(0,5).map((n:any)=><div className="item" key={n.id}><Link to={b+'/notes'}>{n.title}</Link></div>):<p>A blank page for your next idea.</p>},
 goal_progress:{module:'goals',title:'Goals',render:(d,b)=>d.goals?.length?d.goals.slice(0,3).map((g:any)=><div className="item" key={g.id}><Link to={b+'/goals'}>{g.title}</Link><p className="muted">{g.progress}% complete</p><progress value={g.progress} max={100} aria-label={g.title}/></div>):<p>Choose a goal that matters to you.</p>},
 progress_summary:{module:'analytics',title:'Your progress',render:d=><div><div className="metric">{d.progress?.completionRate||0}%</div><p>{d.progress?.done||0} tasks completed</p><progress value={d.progress?.completionRate||0} max={100} aria-label="Task completion"/></div>},
};
export default function Dashboard(){
 const {workspaceId}=useParams();const base='/workspaces/'+workspaceId;const dashboard=useResource<any>(base+'/dashboard');const data=useResource<any>(base+'/dashboard/data');const modules=useResource<any[]>(base+'/modules');const catalog=useResource<any[]>('/modules/catalog');const widgets=useResource<any[]>('/widgets/catalog');const write=useWrite();const editing=useUI(s=>s.editing);const setEditing=useUI(s=>s.setEditing);const [customize,setCustomize]=useState(false);const [tab,setTab]=useState('Modules');const [draft,setDraft]=useState<Layout[]|null>(null);
 const enabled=new Set(modules.data?.filter(m=>m.enabled).map(m=>m.moduleKey));const priority=dashboard.data?.settings?.priorityTopic;
 const visible=(dashboard.data?.widgets||[]).filter((w:any)=>enabled.has(w.catalog.moduleKey)).sort((a:any,b:any)=>Number(b.catalog.moduleKey===priority)-Number(a.catalog.moduleKey===priority)||a.position-b.position);
 const layout=visible.map((w:any,index:number)=>({i:w.id,x:priority?(index%3)*4:w.x,y:priority?Math.floor(index/3)*3:w.y,w:priority?4:w.w,h:w.h,minW:2,minH:2}));
 function save(){write.mutate({path:base+'/dashboard/layout',method:'PUT',body:{items:(draft||layout).map(({i,x,y,w,h}:Layout)=>({id:i,x,y,w,h}))}},{onSuccess:()=>{setEditing(false);setDraft(null);}});}
 return <><div className="page-heading"><div><p className="muted">YOUR PERSONAL WORKSPACE</p><h1>A little focus goes a long way.</h1><p>Make today work for you.</p></div><div className="actions"><button className="secondary" onClick={()=>editing?save():setEditing(true)} disabled={write.isPending}>{editing?'Save layout':'Edit layout'}</button><button className="primary" onClick={()=>setCustomize(true)}>Customize workspace</button></div></div><QueryState query={dashboard}/><QueryState query={data}/>{!dashboard.isPending&&!visible.length&&<div className="panel empty"><h2>Make this space yours</h2><p>Enable a module and add your first widget.</p><button className="primary" onClick={()=>setCustomize(true)}>Add widgets</button></div>}
 <Grid layouts={{lg:layout,md:layout,sm:visible.map((w:any,i:number)=>({i:w.id,x:0,y:i*3,w:1,h:w.h}))}} breakpoints={{lg:1100,md:700,sm:0}} cols={{lg:12,md:12,sm:1}} rowHeight={80} margin={[18,18]} isDraggable={editing} isResizable={editing} draggableHandle=".drag-handle" onDragStop={l=>setDraft(l)} onResizeStop={l=>setDraft(l)}>
 {visible.map((widget:any)=><section key={widget.id} className="panel widget"><header className="widget-header"><h3 className={editing?'drag-handle':''}>{editing?'? ':''}{widget.title||registry[widget.widgetType]?.title||widget.catalog.name}</h3>{editing&&<button aria-label={'Remove '+widget.catalog.name} onClick={()=>write.mutate({path:base+'/dashboard/widgets/'+widget.id,method:'DELETE'})}>?</button>}</header>{data.data&&(registry[widget.widgetType]?.render(data.data,'/w/'+workspaceId)||<p>This module is planned for a later phase. Add a core productivity widget to get started.</p>)}</section>)}</Grid>
 <Drawer isOpen={customize} onClose={()=>setCustomize(false)} title="Customize workspace"><div className="tabs" role="tablist">{['Modules','Widgets','Priority'].map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Modules'&&<div className="stack">{catalog.data?.filter(m=>['tasks','notes','calendar','goals','analytics'].includes(m.key)).map(m=><label className="row item" key={m.key}><div><h3>{m.name}</h3><p className="muted">{m.description}</p></div><input type="checkbox" checked={enabled.has(m.key)} disabled={write.isPending} onChange={e=>write.mutate({path:base+'/modules/'+m.key,method:'PUT',body:{enabled:e.target.checked}})}/></label>)}</div>}{tab==='Widgets'&&<div className="stack">{widgets.data?.filter(w=>registry[w.type]).map(w=><div className="row item" key={w.type}><div><h3>{w.name}</h3><p className="muted">{w.description}</p></div><button className="secondary" disabled={!enabled.has(w.moduleKey)||write.isPending} onClick={()=>write.mutate({path:base+'/dashboard/widgets',body:{widgetType:w.type,x:0,y:visible.length*3,w:4,h:3,position:visible.length}})}>Add</button></div>)}</div>}{tab==='Priority'&&<div className="stack"><p>Bring the things that matter most to the top, on every screen.</p><label>Focus area<select value={priority||''} onChange={e=>write.mutate({path:base+'/dashboard/settings',method:'PATCH',body:{priorityTopic:e.target.value}})}><option value="">My custom layout</option>{catalog.data?.filter(m=>enabled.has(m.key)).map(m=><option key={m.key} value={m.key}>{m.name}</option>)}</select></label></div>}</Drawer></>;
}
