import { useState, useEffect, useRef, FormEvent } from 'react';import { useParams } from 'react-router-dom';import { useEditor, EditorContent } from '@tiptap/react';import StarterKit from '@tiptap/starter-kit';
import { useResource, useWrite } from '../lib/queries';import { api } from '../lib/api';import { Modal } from '../components/ui/Modal';import { QueryState } from '../components/ui/QueryState';
function NoteEditor({note,base}:{note:any;base:string}){
 const [status,setStatus]=useState('Saved');const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const pending=useRef('');const saving=useRef(Promise.resolve());
 function persist(body:string){setStatus('Saving?');saving.current=saving.current.catch(()=>{}).then(async()=>{await api(base+'/notes/'+note.id,'PATCH',{body});setStatus('Saved');}).catch(()=>{setStatus('Could not save. Keep this note open and retry.');});}
 const editor=useEditor({extensions:[StarterKit],content:note.body||'',onUpdate:({editor})=>{pending.current=editor.getHTML();setStatus('Unsaved changes');clearTimeout(timer.current);timer.current=setTimeout(()=>persist(pending.current),700);}});
 useEffect(()=>()=>{clearTimeout(timer.current);if(pending.current)persist(pending.current);},[]);
 return <div className="stack"><div className="actions"><button type="button" className="secondary" onClick={()=>editor?.chain().focus().toggleBold().run()}>Bold</button><button type="button" className="secondary" onClick={()=>editor?.chain().focus().toggleItalic().run()}>Italic</button><button type="button" className="secondary" onClick={()=>editor?.chain().focus().toggleBulletList().run()}>List</button><button type="button" className="secondary" onClick={()=>{clearTimeout(timer.current);persist(editor?.getHTML()||'');}}>Save now</button></div><EditorContent editor={editor}/><p role="status" className="form-status">{status}</p></div>;
}
export default function Notes(){
 const {workspaceId}=useParams();const base='/workspaces/'+workspaceId;const [search,setSearch]=useState('');const [category,setCategory]=useState('');const [selected,setSelected]=useState<any>(null);const [create,setCreate]=useState(false);const [manage,setManage]=useState(false);
 const notes=useResource<any[]>(base+'/notes?q='+encodeURIComponent(search)+(category?'&categoryId='+category:''));const categories=useResource<any[]>(base+'/note-categories');const write=useWrite();
 async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const note=await write.mutateAsync({path:base+'/notes',body:{title:f.get('title'),...(f.get('categoryId')?{categoryId:f.get('categoryId')}:{})}});setCreate(false);setSelected(note);}
 return <><div className="page-heading"><div><h1>Notes</h1><p>A home for ideas, context, and clarity.</p></div><button className="primary" onClick={()=>setCreate(true)}>+ New note</button></div><div className="actions" style={{marginBottom:20}}><input aria-label="Search notes" placeholder="Search notes?" value={search} onChange={e=>setSearch(e.target.value)} style={{maxWidth:300}}/><select aria-label="Category" value={category} onChange={e=>setCategory(e.target.value)} style={{maxWidth:220}}><option value="">All categories</option>{categories.data?.map(c=><option key={c.id} value={c.id}>{c.parentId?'? ':''}{c.name}</option>)}</select><button className="secondary" onClick={()=>setManage(true)}>Categories</button></div><QueryState query={notes} empty={!notes.data?.length}/><div className="grid">{notes.data?.map(n=><button className="panel stack" style={{textAlign:'left'}} key={n.id} onClick={()=>setSelected(n)}><h3>{n.pinned?'? ':''}{n.title}</h3><p className="muted">Updated {new Date(n.updatedAt).toLocaleDateString()}</p></button>)}</div><Modal isOpen={create} onClose={()=>setCreate(false)} title="New note"><form onSubmit={e=>void add(e).catch(()=>{})}><label>Title<input name="title" required/></label><label>Category<select name="categoryId"><option value="">Uncategorized</option>{categories.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="primary" disabled={write.isPending}>Create note</button></form></Modal><Modal isOpen={!!selected} onClose={()=>{setSelected(null);void notes.refetch();}} title={selected?.title}>{selected&&<><NoteEditor key={selected.id} note={selected} base={base}/><div className="actions" style={{marginTop:16}}><button className="secondary" onClick={()=>write.mutate({path:base+'/notes/'+selected.id,method:'PATCH',body:{pinned:!selected.pinned}},{onSuccess:()=>setSelected({...selected,pinned:!selected.pinned})})}>{selected.pinned?'Unpin':'Pin note'}</button><button className="danger" onClick={()=>write.mutate({path:base+'/notes/'+selected.id,method:'DELETE'},{onSuccess:()=>setSelected(null)})}>Delete note</button></div></>}</Modal><Modal isOpen={manage} onClose={()=>setManage(false)} title="Note categories"><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);write.mutate({path:base+'/note-categories',body:{name:data.get('name'),...(data.get('parentId')?{parentId:data.get('parentId')}:{})}},{onSuccess:()=>form.reset()});}}><label>Name<input name="name" required/></label><label>Parent<select name="parentId"><option value="">None</option>{categories.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="primary" disabled={write.isPending}>Add category</button></form>{categories.data?.map(c=><div className="row item" key={c.id}><span>{c.name}</span><button className="danger" onClick={()=>write.mutate({path:base+'/note-categories/'+c.id,method:'DELETE'})}>Delete</button></div>)}</Modal></>;
}
