import { useState, FormEvent } from 'react';import { useParams } from 'react-router-dom';import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useResource, useWrite } from '../lib/queries';import { api } from '../lib/api';import { Modal } from '../components/ui/Modal';import { QueryState } from '../components/ui/QueryState';import { useUI } from '../stores/ui';
export default function Tasks(){
 const {workspaceId}=useParams();const base='/workspaces/'+workspaceId;const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [selected,setSelected]=useState<any>(null);
 const path=base+'/tasks?q='+encodeURIComponent(search)+(status?'&status='+status:'');const tasks=useResource<any[]>(path);const goals=useResource<any[]>(base+'/goals');const write=useWrite();const cache=useQueryClient();const notify=useUI(s=>s.notify);
 const toggle=useMutation({mutationFn:(task:any)=>api(base+'/tasks/'+task.id+'/complete','POST',{completed:task.status!=='done'}),onMutate:async task=>{await cache.cancelQueries({queryKey:[path]});const previous=cache.getQueryData([path]);cache.setQueryData([path],(rows:any[])=>rows?.map(t=>t.id===task.id?{...t,status:t.status==='done'?'todo':'done'}:t));return {previous};},onError:(error,_,context)=>{cache.setQueryData([path],context?.previous);notify(error.message);},onSettled:()=>cache.invalidateQueries()});
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const body:any={title:f.get('title'),description:f.get('description'),priority:f.get('priority'),status:f.get('status')};if(f.get('dueAt'))body.dueAt=new Date(String(f.get('dueAt'))).toISOString();if(f.get('goalId'))body.goalId=f.get('goalId');
 await write.mutateAsync({path:base+'/tasks'+(selected.id?'/'+selected.id:''),method:selected.id?'PATCH':'POST',body});setSelected(null);}
 return <><div className="page-heading"><div><h1>Tasks</h1><p>Make space for what matters.</p></div><button className="primary" onClick={()=>setSelected({})}>+ Add task</button></div><div className="actions" style={{marginBottom:18}}><input aria-label="Search tasks" placeholder="Search tasks?" value={search} onChange={e=>setSearch(e.target.value)} style={{maxWidth:350}}/><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)} style={{maxWidth:180}}><option value="">All statuses</option>{['todo','in_progress','done','archived'].map(s=><option key={s}>{s}</option>)}</select></div><div className="panel"><QueryState query={tasks} empty={!tasks.data?.length}/>{tasks.data?.map(task=><div className="row item" key={task.id}><input aria-label={'Complete '+task.title} type="checkbox" checked={task.status==='done'} disabled={toggle.isPending} onChange={()=>toggle.mutate(task)}/><button className={'task-title '+(task.status==='done'?'completed':'')} onClick={()=>setSelected(task)}>{task.title}<div className="muted">{task.dueAt?new Date(task.dueAt).toLocaleString():'No deadline'}</div></button><span className="badge">{task.priority}</span></div>)}</div><Modal isOpen={!!selected} onClose={()=>setSelected(null)} title={selected?.id?'Task details':'Quick add task'}>{selected&&<form onSubmit={e=>void save(e).catch(()=>{})}><label>Title<input name="title" defaultValue={selected.title} required maxLength={300}/></label><label>Description<textarea name="description" defaultValue={selected.description}/></label><div className="field-grid"><label>Status<select name="status" defaultValue={selected.status||'todo'}>{['todo','in_progress','done','archived'].map(s=><option key={s}>{s}</option>)}</select></label><label>Priority<select name="priority" defaultValue={selected.priority||'medium'}>{['low','medium','high','urgent'].map(p=><option key={p}>{p}</option>)}</select></label></div><label>Due date<input name="dueAt" type="datetime-local" defaultValue={selected.dueAt?new Date(+new Date(selected.dueAt)-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''}/></label><label>Goal<select name="goalId" defaultValue={selected.goalId||''}><option value="">No goal</option>{goals.data?.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><div className="actions"><button className="primary" disabled={write.isPending}>Save task</button>{selected.id&&<button type="button" className="danger" disabled={write.isPending} onClick={()=>void write.mutateAsync({path:base+'/tasks/'+selected.id,method:'DELETE'}).then(()=>setSelected(null)).catch(()=>{})}>Delete task</button>}</div></form>}</Modal></>;
}
